<%@ page language="java" contentType="text/html; charset=ISO-8859-1" import="java.util.Date" info="Directive Demo" buffer="8kb" isELIgnored="false" isErrorPage="false"
    pageEncoding="ISO-8859-1" errorPage="error.jsp" isThreadSafe="true"  autoFlush="true" session="true" %>
<%@ include file="includeDirective.jsp" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Directive Demo</title>
</head>
<body>
<h1> Page Directive Attributes </h1>
Import  =  <%= new Date() %>  <br>
Language = Specify language for jsp page <br>
ContentType = Specify content type of jsp page <br>
Info = To be read by getservletInfo() <br>
Buffer = Output generated by jsp page <br>
autoFlush = To perform operation when buffer is full <br>
isELIgnored = To set flag for expression language use <br>
isErrorPage = To show current jsp is error page or not <br>
errorPage = Specify error page for jsp page <br>
isThreadSafe = To set page as thread safe <br>
pageEncoding = Encoding of page <br>
session = To indicate use of HttpSession <br>
extends = To extends java class in jsp <br>

<h1> Taglib Directive </h1>
<c:out value="${'This is output from taglib directive'}"/>  
</body>

</html>